"use client";
import React from "react";
// import './globals.css'
import "@/scss/globals.scss";
import {  Work_Sans } from "next/font/google";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import Navbar from "@/components/shared-components/Navbar/Navbar";

const work_Sans = Work_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={work_Sans.className}>
        <Provider store={store}>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
